### ISSUE TITLE
searchInstagram - Error in curl::curl_fetch_memory(url, handle = handle) 

### ISSUE THREAD

**Issue by mobcdi** [pablobarbera/instaR#13]
When I run the following command it starts to return values but then errors out

Comments <- searchInstagram(tag="MySearchTerm",token = my_oauth, n=500)
20 posts 40  60  80  100  120  140  160  180  198  
Error in curl::curl_fetch_memory(url, handle = handle) : 
Couldn't resolve host name

If I change n=100 the command returns a dataframe successfully but if you search directly on instragram  you can see that n could be larger (with my search query over 300 items were tagged)

Running n =198 works but n=199 returns the error message above

**Comment by pablobarbera** [comment]
This commit fixes the bug that was giving the error message. However, I think the total number of pictures you receive back is lower than what the website reports because on the website you may be able to see private pictures from people you follow, and the tag count includes private pictures as well. I double checked and this function does return everything that the API returns, so if there's any difference, Instagram is to blame! :)

**Comment by pablobarbera** [comment]
And thanks again for reporting this!
