### ISSUE TITLE
Error in callApi and get Usser

### ISSUE THREAD

**Issue by FerDoranNie** [pablobarbera/instaR#32]
Hi Pablo. I have the next problem:
I type this:
vocho <- searchInstagram(tag="volkswagenmexico", token=mytoken)
and I have
Error in instaR::getUser(username = "volkswagenmexico", token = my_oauth) :
Error. User name not found.
I check the code with debug and the problem is callAPI. I appreciate so much your help.
Thanks

**Comment by diegocgaona** [comment]
I'm having the same error, with getUser and getFollowers too.
I tried both versions, from CRAN and GitHub.

**Comment by paolof89** [comment]
Seems that the problem is due to a new Instagram policy.
Try with getUser(username = YOURACTUALUSERNAME,token = my_oauth)

You will able to retrieve your stats

**Comment by projectyotta** [comment]
Having the same issue. I am using the following line : 

obama <- searchInstagram("#obama", my_oauth, n=20, folder="obama")

It is working when I search on the instagram website. Seems to be a policy change by instagram.

**Comment by pablobarbera** [comment]
Hi everyone -- yeah, sadly it's all due to the recent changes in the Instagram API. All this data is not available anymore unless you get permission from Instagram when you create the application. Nothing I can do on my end to fix this, sorry! I added more informative error messages when this happens.
